int _putchar();
int print_alphabet();
int print_alphabet_x10();
int _islower();
int _isalpha();
int print_sign();
int _abs();
int print_last_digit();
void jack_bauer();
void times_table(void);
int add(int, int);
